### ISSUE TITLE
The buttons on the update menu do nothing.

### ISSUE THREAD

**Issue by Greyevel** [kinmunity/kinnect-desktop#1]
Sorry I hit enter not realising it would submit it.

**Describe the bug**
When you open the client and it brings up the update menu neither the skip or install update buttons do anything when clicked.

**To Reproduce**
1. Open the client (If open already close it first)
2. If there's an update it will tell you
3. the buttons will do nothing

**Expected behavior**
I expect the install update button to automatically update the client for me, and the skip button to close the window.

OS: Windows 10 1803
Kinnect version: 1.0.5

**Comment by Greyevel** [comment]
I manually updated to 1.0.6. I will let you know if the issue persists when the next update is available.

**Comment by naiaokami** [comment]
Thank you for reporting, I confirm this bug.  Working on it now!

**Comment by naiaokami** [comment]
This issue has been fixed in 1.0.7; thank you for letting me know about it!
